openapi: 3.0.0
info:
  title: Laka accounts fleets API
  description: Laka API (next)
  version: '2024-09-01'
  contact: {}
servers:
- url: https://api.uat.laka.co
  description: UAT
- url: https://api-{region}.app.laka.co
  description: Production
  variables:
    region:
      enum:
      - nl
      - fr
      - gb
      default: gb
tags:
- name: fleets
paths:
  /v3/fleets/claim:
    post:
      operationId: FleetController_createFleetClaim
      summary: Create Fleet Claim
      description: Create a claim for fleet product.
      parameters:
      - name: x-api-region
        in: header
        style: simple
        description: The API region of your interaction. In most cases, this will match the customer region
        schema:
          type: string
      - name: x-api-language
        in: header
        description: Where applicable, the language for any textual content we may send to the customer.
        style: simple
        schema:
          type: string
      responses:
        '201':
          description: Creates a fleet claim
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFleetClaimResponse'
      tags:
      - fleets
      security:
      - x-api-key: []
components:
  schemas:
    CreateFleetClaimResponse:
      type: object
      properties:
        message:
          type: string
        claim:
          type: string
        reference:
          type: string
      required:
      - message
      - claim
      - reference
  securitySchemes:
    x-api-key:
      type: apiKey
      in: header
      name: x-api-key
